language: java
jdk:
- openjdk8

sudo: false
install: true

addons:
  sonarcloud:
    organization: "fjdearcos"
    token:
      secure: "MHoP3qIo4MIgHOFcJUhVZmil+HTMFnB+/WxQT8VtUh78PcWFJqet9tyJopKe3snSP6Ny8fEg2FAD33OJRXRo1UddEs7qbvXR/eF7JrieEY7JjQkmbHQCp8wvnBvHgUdVCAtCweN7McDOiJ3U53mAcbOO0PWdPzSEWIsUYONfMcsG/yGPNFOjQa5rg02HwxKPGR5/XNJHnsJ7OTAWGRxxPqfGOUPOS/KpmnhoWDQThWf1eairca8Kd+acDDvKIth3N9Tqz7hRX3KipTjSaXu31roFqjedHsLkyznddOuyEZLb6lD8Q0ZMA88KFVOVC4m4F7XFj3NERW4YVG2izrZfsr6jZjSMrLDOVPpPrQQ68a/xTJyXyZwtevhKImQCQ42jwdCfni9325ccI6OJrUCQODQxmbQ3mOhCvgW6I7lQ8RcJLOhkm5i/EMmXIMqsWgruYQui7qTjjKMoFWtK7l0saCEDV5rY9a8E9sMlDl0JtorMlHsvi2AUiXamJI50hCY75iU2C/Vy+0nwLDY/SDMEUBQH74VBFgKAayu4CtMXGxHGFByU6w53qv7+IzMHT3teAs8BP77uThCYKweukJZ38gV+vLr6zBe/tZW/7nXLVlgyv72taiZW29x8ecdl/IWZmg92t/DKAGjmV3sKfYxGE6JFtSRxglK5q79UY576C4k="

script:
  - mvn clean verify sonar:sonar

cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
